services:
  - type: web
    name: billing-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/billingsoftware-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DB_URL
        fromEnvVar: DB_URL
      - key: DB_USERNAME
        fromEnvVar: DB_USERNAME
      - key: DB_PASSWORD
        fromEnvVar: DB_PASSWORD
      - key: AWS_ACCESS_KEY
        fromEnvVar: AWS_ACCESS_KEY
      - key: AWS_SECRET_KEY
        fromEnvVar: AWS_SECRET_KEY
      - key: AWS_REGION
        fromEnvVar: AWS_REGION
      - key: AWS_BUCKET
        fromEnvVar: AWS_BUCKET
      - key: JWT_SECRET
        fromEnvVar: JWT_SECRET
      - key: RAZORPAY_KEY_ID
        fromEnvVar: RAZORPAY_KEY_ID
      - key: RAZORPAY_KEY_SECRET
        fromEnvVar: RAZORPAY_KEY_SECRET
